### ISSUE TITLE
Pls Stop updating WT Bot.

### ISSUE THREAD

**Issue by Bappsack1994** [drgoku282/PKMN-NTR#117]
Man, u get my Respect for beeing a great dev, looked into your Source awesome, but u should stop updating the WT Bot, many Streamers using your Bot and arent thankfull for that, they grab and gain money with your work.

**Comment by tonyrayo** [comment]
This is 100% my opinion, but while I think it's fair to request fewer script-breaking changes (perhaps create a roadmap and update in bulk less often or plan a way to add new features that doesn't break compatibility), AFAIK this isn't a project aimed at the streaming community and I personally have little sympathy for the possible net loss of people freely using open source tools.

**Comment by TWonderchild** [comment]
All the streamers making money with wondertrading bots arent even using this one - i don't see the point.

**Comment by drgoku282** [comment]
I started this as a personal project, but decided to make it public. To be honest, I really don't care too much about who uses the program and if they make money with it.

Also, if the bots are buggy, is mostly because I haven't found a better way to do it, but as long I can send some pokes on Wonder Trade Wednesdays, the bot is good enough for me.

But that's the great part of releasing the source of the program, people can just fork this and do their own upgrades and eventually everyone benefits from it. For example, [Ledybot ](https://github.com/olliz0r/Ledybot) is based on a old release of this program.
