### ISSUE TITLE
Rosalina Menu InputRedirection support

### ISSUE THREAD

**Issue by Real96** [drgoku282/PKMN-NTR#130]
Will you add the support for InputRedirection from Rosalina menu? It will be really useful and it won't need anymore the installation of the CIA

**Comment by drgoku282** [comment]
Short answer: Not in plans.

Long answer: Rosalina and the current implementation of controller implementation are somewhat different, and I really don't know how to deal with Rosalina (this also makes me to keep using NTR debugger and not Rosalina debugger). A lot of things in the program would have to be rewritten in order to do that, since 3DS is approaching EOL, I don't think it's worth the time, because at my (really slow) developing speed, it would take several months to make the program work with Rosalina.

**Comment by lucasliet** [comment]
I really think it would be worth the time, the homebrew scenario in the 3DS is wonderful and worth using at any time.
plus I really wanted that feature right now 1 year in the future, lol
