### ISSUE TITLE
Make it easier to get to .HaX mode

### ISSUE THREAD

**Issue by Naturally-Delicious** [drgoku282/PKMN-NTR#153]
Make it like how PKHeX does it, rename the file to PKH**a**X. It's much easier then going into terminal and re-typing the same thing each time we want to open the program. The normal version is not even worth using anymore since we can't inject so called "illegal" Pokemon. May I please ask why this feature is even in here? Injecting an illegal pokemon into the game is not going to break it, cause you to get a ban, or any other theory that people try to keep pushing. PKHeX has nothing like this and it has a way higher chance of corrupting your save.

**Comment by ghost** [comment]
I believe you can just create a shortcut that has the parameter appended to auto launch in "Hax" mode without having to use the terminal.

**Comment by AMurloc** [comment]
Write a batch file in the root of the application and put: "PKMN-NTR -hax" into it

**Comment by drgoku282** [comment]
This program has a higher change of breaking your game or corrupting your save file than PKHeX, since it writes directly to the 3DS ram, even reading reading certain parts of the memory makes the game freeze.

In fact, I put the illegal mode because people requested it, it wasn't a planned feature in the first place. Also due its on-the-air feature, it can be exploited, I put some safety checks but that can't stop people form modifying the source code.

I remember somebody on GBATemp was able to send an Egg through Wonder Trade (by writing on the memory using the same approach as this program), and that are the kind of things I want to avoid.

Maybe modifying the memory in certain ways will not get you banned right now, but nobody knows when or if nintendo will change their checks, and if it's possible to reduce the risk of getting banned I think the safety checks are worth it.

So, I won't make illegal mode easier to access, I think it's fine right now, not that easy (for the noobs) and not too annoying for everyone else. I'd like to remove it completely but I also understand that people like the feature so it is staying the way it is.

**Comment by Naturally-Delicious** [comment]
Thanks drgoku, your work on this project is legendary. sorry I have been bugging you so much about this 

@Loadie @AMurloc Ty for the ideas, I'll try them when I am home.

**Comment by Naturally-Delicious** [comment]
@Loadie creating shortcut doesn't work

@Amurloc do I literally put JUST "PKMN-NTR -had" into a batch file? I don't know how that's supposed to work. And I don't know how to create a bath file?

**Comment by AMurloc** [comment]
Alright, create a new text file by right clicking > new > Text Document. Name it whatever you like. Open it, type "\<Path to PKMN-NTR\>" -hax and change the .txt at the end to .bat.
