### ISSUE TITLE
Gen 7 breeding bot optimization

### ISSUE THREAD

**Issue by imaboy321** [drgoku282/PKMN-NTR#41]
instead of requiring the bot to move and potentially break, why pick up 5 eggs, read them while in the party, and if a match is not found pick up 5 more and send the previous batch to the pc with the new feature.

**Comment by drgoku282** [comment]
I can read them from the party, the problem is moving them from the party to the PC, because data size is different (260 vs 232 bytes), but that has a workaround. The main problem is deleting pokémon from the party safely., mostly because the pokemon are not next to each other in the RAM, there are some data in between which I don't know how to manipulate in order to free the space.

**Comment by imaboy321** [comment]
Well what I mean is use Gen 7's new "send to box" feature. Pick up the eggs and if the party is full, it will ask you to replace a pokemon or send it to the box. When it sends it to the box, it starts at the last box viewed and continues from there. I have a feeling the last box viewed is somewhere in the RAM and if not then the user could just set it before use.

**Comment by drgoku282** [comment]
I forgot that feature completely, yes that is possible, thanks for the suggestion.
