### ISSUE TITLE
Wondertrade bot fails when receiving a Pokemon that learns a move upon evolution by trade

### ISSUE THREAD

**Issue by TLATER** [drgoku282/PKMN-NTR#71]
I believe I just encountered this bug after receiving a Phantump.

Interestingly, presumably since some of the touchscreen areas match up, it still manages to get back to the plaza after deleting the third move, but then appears to stop.

I waited for about a minute to see if it would continue, please don't lynch me if it actually does continue after 90 seconds, considering the trade failed due to time-out - in that case there is maybe some room for optimization here?

**Comment by AliasGprime** [comment]
Was just about to come here and say the same thing. The bot manage the trade evo really well but get stuck when the pokemon is learning a new move. Which happen pretty often now in Gen 7. I think I even encounter a pokemon who learned 2 moves, one after another, but I'm not 100% sure. I read the source code and It doesn't seem to have anything coded to handle the new moves. I may try to solve it on my side. For my needs, It could just smash and press "A" non stop to learn the new move in the first slot and be done. Since I only wondertrade pk7 files and I alway overwrite the first slot of the first box. But since I'm a novice in c# and with my low understanding of memory data coming from the game, I don't know if I can do it. I may need to wait that it happen again to know what happening exactly with the logs window.

Also, I may take this message to thanks the originals coders for this wonderfull software. I managed to modify it for my personnal needs and it helped me alot. Thanks to you guys!

**Comment by drgoku282** [comment]
I thought this was fixed a little ago, but it seems it broke in some pont of the past, will look on it,

**Comment by drgoku282** [comment]
I hope this fix helps somehow, most errors are caused because somehow the game tells the program the trade has finished when it doesn't. No promises on two move learning, it might or might not work, depending on thow the values on ram are changed.

**Comment by codster88** [comment]
Is this fixed in the newest version?
