### ISSUE TITLE
Cannot build the program myself

### ISSUE THREAD

**Issue by AyanamiRei1** [drgoku282/PKMN-NTR#74]
Hi I'm getting this issue when trying to build this 

> Error    CS1061    'LegalityAnalysis' does not contain a definition for 'VerboseReport' and no extension method 'VerboseReport' accepting a first argument of type 'LegalityAnalysis' could be found (are you missing a using directive or an assembly reference?

**Comment by drgoku282** [comment]
Are you sure you have PKHeX source code as descirbed in the wiki (See compilation). If so, it seems you might be using a recent commit of PKHeX, last stable version was built with 20170311 version.

**Comment by drgoku282** [comment]
Confirmed, caused by a recent commit on PKHeX source. Currently working on implementing 20170318 on the application. Will not fix this until a new stable version of PKHeX is released. Next stable version will use the following commit for building;

https://github.com/kwsch/PKHeX/commit/910689690931abb0fd0978ef2ad07d13126175f6

**Comment by drgoku282** [comment]
Building using recent commits from PKHeX will now be discussed in #82.
